"""second migration

Revision ID: 3bdfdceb62fc
Revises: cf2df4d85421
Create Date: 2023-10-15 16:19:33.836244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdfdceb62fc'
down_revision = 'cf2df4d85421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
