"""second migration

Revision ID: 47e0ebc534d4
Revises: 3bdfdceb62fc
Create Date: 2023-10-15 16:24:49.060902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e0ebc534d4'
down_revision = '3bdfdceb62fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
