"""second migration

Revision ID: 6b9acf179e63
Revises: 694e0e64998b
Create Date: 2023-10-15 15:38:17.413276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9acf179e63'
down_revision = '694e0e64998b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('close_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
